# Generated by Django 4.0 on 2021-12-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Course_Number', models.IntegerField(unique=True)),
                ('Instructor_Name', models.CharField(max_length=60)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
